<?php

/**
 * Core user accounts for Pharmezel (buyer, admin, superadmin).
 *
 * @table users
 * @pk user_id
 * @see \App\Models\User
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('users', function (Blueprint $table) {

            $table->id('user_id');

            // Personal info
            $table->string('first_name');
            $table->string('last_name');
            $table->date('date_of_birth')->nullable();

            // Authentication
            $table->string('email')->unique();
            $table->string('password');

            // Contact
            $table->string('contact_number')->unique();

            // Referral system
            $table->string('referral_code')->nullable()->unique();      // generated by system
            $table->string('referrer_code_used')->nullable();                       // code used during signup

            // Role system
            $table->string('role')->default('user');        // admin or user

            // Tracking
            $table->timestamp('date_registered')->useCurrent();

            // Laravel automatic timestamps
            $table->timestamps();

        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('users');
    }
};